CREATE TABLE "AppAuditLogRecord" (
  "id" INTEGER NOT NULL,
  "companyId" INTEGER NOT NULL,
  "actorUserId" INTEGER,
  "actorUserName" TEXT NOT NULL,
  "actorUsername" TEXT NOT NULL,
  "actorRole" TEXT NOT NULL,
  "actorKind" TEXT NOT NULL,
  "module" TEXT NOT NULL,
  "actionKey" TEXT NOT NULL,
  "actionLabel" TEXT NOT NULL,
  "targetType" TEXT NOT NULL,
  "targetId" TEXT NOT NULL,
  "targetLabel" TEXT NOT NULL,
  "summary" TEXT NOT NULL,
  "impactSummary" TEXT NOT NULL,
  "severity" TEXT NOT NULL,
  "result" TEXT NOT NULL,
  "relatedCompanyIds" INTEGER[],
  "details" JSONB NOT NULL,
  "occurredAt" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "AppAuditLogRecord_pkey" PRIMARY KEY ("id")
);
